/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import logica.Congregante;
import logica.Iglesia;
import logica.ManejaBD;

/**
 *
 * @author davi1
 */
public class AdminCongregante extends javax.swing.JDialog {
    private DefaultListModel lista1;
    private DefaultListModel lista2;
    private ArrayList<Congregante> list;
    private Congregante foco;
    private ArrayList<Congregante> lAux;

    /**
     * Creates new form AgregarCongregante
     */
    public AdminCongregante(java.awt.Frame parent, boolean modal, ArrayList<Congregante> alC) {
        super(parent, modal);
        initComponents();
        list = alC;
        agregaListaCongregantes();
        this.setResizable(false); //Deshabilita la opción de maximizar la ventana.
        this.setLocationRelativeTo(null); //Centra la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCongregantes = new javax.swing.JList<>();
        botonAgregaCongregante = new javax.swing.JButton();
        botonEditarCongregante = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();
        jTextBuscar = new javax.swing.JTextField();
        btnVerC = new javax.swing.JButton();

        jButton4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar congregantes");

        listaCongregantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCongregantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaCongregantes);

        botonAgregaCongregante.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        botonAgregaCongregante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/more_32.png"))); // NOI18N
        botonAgregaCongregante.setText("Agregar Congregante");
        botonAgregaCongregante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregaCongreganteActionPerformed(evt);
            }
        });

        botonEditarCongregante.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        botonEditarCongregante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pen.png"))); // NOI18N
        botonEditarCongregante.setText("Editar Congregante");
        botonEditarCongregante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarCongreganteActionPerformed(evt);
            }
        });

        bCerrar.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow_left1.png"))); // NOI18N
        bCerrar.setText("Cerrar");
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });

        jTextBuscar.setText("Ingrese nombre de búsqueda");
        jTextBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextBuscarMouseClicked(evt);
            }
        });
        jTextBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscarActionPerformed(evt);
            }
        });
        jTextBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextBuscarKeyPressed(evt);
            }
        });

        btnVerC.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnVerC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye.png"))); // NOI18N
        btnVerC.setText("Ver Congregante");
        btnVerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(bCerrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAgregaCongregante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVerC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEditarCongregante)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAgregaCongregante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEditarCongregante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregaCongreganteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregaCongreganteActionPerformed
        AgregarCongregante aec = new AgregarCongregante(null, true, list);
        aec.setVisible(true);
        Iglesia ig = new Iglesia();
        list = ig.getListaCongregantes();
    }//GEN-LAST:event_botonAgregaCongreganteActionPerformed

    private void botonEditarCongreganteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarCongreganteActionPerformed
        EditarCongregante ec = new EditarCongregante (null, true, foco);
        ec.setVisible(true);
        Iglesia ig = new Iglesia();
        list = ig.getListaCongregantes();
    }//GEN-LAST:event_botonEditarCongreganteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCerrarActionPerformed

    private void jTextBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBuscarActionPerformed

    private void listaCongregantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCongregantesMouseClicked
        try{
            int ide, posicion = listaCongregantes.locationToIndex(evt.getPoint());
            foco = lAux.get(posicion);
            botonEditarCongregante.setEnabled(true);
            btnVerC.setEnabled(true);
            if (evt.getClickCount() == 2){
                
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_listaCongregantesMouseClicked

    private void jTextBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBuscarKeyPressed
        buscar (jTextBuscar.getText());
    }//GEN-LAST:event_jTextBuscarKeyPressed

    private void jTextBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextBuscarMouseClicked
        jTextBuscar.setText("");
    }//GEN-LAST:event_jTextBuscarMouseClicked

    private void btnVerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCActionPerformed
        InfoCongregante ic = new InfoCongregante(null, true, foco);
        ic.setVisible(true);
    }//GEN-LAST:event_btnVerCActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void agregaListaCongregantes (){
        lista1 = new DefaultListModel();
        this.listaCongregantes.setModel(lista1);
        lAux = new ArrayList<Congregante>();
            for( int i = 0 ; i < list.size() ; i++ ){
                lista1.addElement("<html><font color='blue' face='Comic Sans MS' size='4'>"+list.get(i).getNombres()+" "+list.get(i).getApellidos()+"</font><br><b>Identificación: </b>"
                        + ""+list.get(i).getNumIdentificacion()+"<b> Teléfono: </b>"+list.get(i).getTelefono()+"<b> Celular: </b>"+list.get(i).getCelular()+"</html>");
                lAux.add(list.get(i));
            }
            botonEditarCongregante.setEnabled(false);
            btnVerC.setEnabled(false);
    }
    
    private void buscar (String b){
        lista2 = new DefaultListModel();
        String cad;
        this.listaCongregantes.setModel(lista2);
        lAux = new ArrayList<Congregante>();
        for (int i=0; i<list.size(); i++){
            cad = list.get(i).getNombres().toLowerCase()+" "+list.get(i).getApellidos().toLowerCase();
            int res = cad.indexOf(b.toLowerCase());
            if (res != -1){
                lAux.add(list.get(i));
                lista2.addElement("<html><font color='blue' face='Comic Sans MS' size='4'>"+list.get(i).getNombres()+" "+list.get(i).getApellidos()+"</font><br><b>Identificación: </b>"
                        + ""+list.get(i).getNumIdentificacion()+"<b> Teléfono: </b>"+list.get(i).getTelefono()+"<b> Celular: </b>"+list.get(i).getCelular()+"</html>");
            }
        }
        botonEditarCongregante.setEnabled(false);
        btnVerC.setEnabled(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton botonAgregaCongregante;
    private javax.swing.JButton botonEditarCongregante;
    private javax.swing.JButton btnVerC;
    private javax.swing.JButton jButton4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextBuscar;
    private javax.swing.JList<String> listaCongregantes;
    // End of variables declaration//GEN-END:variables
}
