/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import logica.Congregante;
import logica.Discipulado;
import logica.NotaDiscipulado;

/**
 *
 * @author davi1
 */
public class AgregarEstudiantesDiscipulado extends javax.swing.JDialog {
    private ArrayList<Congregante> aLC;
    private Discipulado d;
    private Congregante foco;
    private DefaultListModel lista1;
    private DefaultListModel lista2;
    private int posicion;
    private ArrayList<Congregante> aux;
    /**
     * Creates new form AgregarMiembrosMinisterio
     */
    public AgregarEstudiantesDiscipulado(java.awt.Frame parent, boolean modal, ArrayList<Congregante> aLC, Discipulado d) {
        super(parent, modal);
        initComponents();
        this.setResizable(false); //Deshabilita la opción de maximizar la ventana.
        this.setLocationRelativeTo(null); //Centra la ventana
        this.aLC = aLC;
        this.aux = aLC;
        this.d = d;
        agregaListaCongregantes ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tBusca = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lCongregantes = new javax.swing.JList<>();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tBusca.setText("Ingrese nombre");
        tBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tBuscaMouseClicked(evt);
            }
        });
        tBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tBuscaKeyPressed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setToolTipText("");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lCongregantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCongregantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lCongregantes);

        btnSalir.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(65, 65, 65))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(tBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (d.agregarEstudiante(d.getIdDiscipulado(), foco.getNumIdentificacion())){
            JOptionPane.showMessageDialog(this, "Estudiante agregado exitosamente!");
            ArrayList<NotaDiscipulado> aLND = d.getEstudiantesMatriculados();
            aLND.add(new NotaDiscipulado (d.getIdDiscipulado(), foco.getNumIdentificacion()));
            d.setEstudiantesMatriculados(aLND);
            tBusca.setText("");
            agregaListaCongregantes ();
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo agregar a la base de datos"
                        , "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void lCongregantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCongregantesMouseClicked
        try{   
            posicion = lCongregantes.locationToIndex(evt.getPoint());
            foco = aux.get(posicion);
            btnAgregar.setEnabled(true);
        }catch(Exception e){}
    }//GEN-LAST:event_lCongregantesMouseClicked

    private void tBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tBuscaMouseClicked
        tBusca.setText("");
    }//GEN-LAST:event_tBuscaMouseClicked

    private void tBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tBuscaKeyPressed
        buscar (tBusca.getText());
    }//GEN-LAST:event_tBuscaKeyPressed
    
    private void agregaListaCongregantes (){
        lista1 = new DefaultListModel();
        this.lCongregantes.setModel(lista1);
        aux = new ArrayList<Congregante>();
            for( int i = 0 ; i < aLC.size() ; i++ ){
                boolean p = true;
                for (int j=0; j<d.getEstudiantesMatriculados().size(); j++){
                    if (aLC.get(i).getNumIdentificacion() == d.getEstudiantesMatriculados().get(j).getIdEstudiante()){
                        p = false; break;
                    }
                } 
                if (p){
                   lista1.addElement("<html><font color='blue' face='Comic Sans MS' size='4'>"+aLC.get(i).getNombres()+" "+aLC.get(i).getApellidos()+"</font><br><b>Identificación: </b>"
                        +aLC.get(i).getNumIdentificacion());
                   aux.add(aLC.get(i));
                }   
            }
            btnAgregar.setEnabled(false);
    }
    
    private void buscar (String b){
        lista2 = new DefaultListModel();
        String cad;
        this.lCongregantes.setModel(lista2);
        aux = new ArrayList<Congregante>();
        for (int i=0; i<aLC.size(); i++){
            boolean p = true;
            for (int j=0; j<d.getEstudiantesMatriculados().size(); j++){
                if (aLC.get(i).getNumIdentificacion() == d.getEstudiantesMatriculados().get(j).getIdEstudiante()){
                    p = false; break;
                }
            }
            if (p){
                cad = aLC.get(i).getNombres().toLowerCase()+" "+aLC.get(i).getApellidos().toLowerCase();
                int res = cad.indexOf(b.toLowerCase());
                if (res != -1){
                    lista2.addElement("<html><font color='blue' face='Comic Sans MS' size='4'>"+aLC.get(i).getNombres()+" "+aLC.get(i).getApellidos()+"</font><br><b>Identificación: </b>"
                        +aLC.get(i).getNumIdentificacion());
                    aux.add(aLC.get(i));
                }
            }
        }
        btnAgregar.setEnabled(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lCongregantes;
    private javax.swing.JTextField tBusca;
    // End of variables declaration//GEN-END:variables
}
