/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.Congregante;
import logica.Discipulado;
import logica.NotaDiscipulado;

/**
 *
 * @author davi1
 */
public class AgregarVerNota extends javax.swing.JDialog {
    private NotaDiscipulado nD;
    private ArrayList<Congregante> aLC;
    private Discipulado d;
    /**
     * Creates new form AgregarNota
     */
    public AgregarVerNota(java.awt.Frame parent, boolean modal, NotaDiscipulado nD, ArrayList<Congregante> aLC, Discipulado d) {
        super(parent, modal);
        initComponents();
        this.setResizable(false); //Deshabilita la opción de maximizar la ventana.
        this.setLocationRelativeTo(null); //Centra la ventana
        this.aLC = aLC;
        this.d = d;
        this.nD = nD;
        llenarVentana ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lAlumno = new javax.swing.JLabel();
        lIdentificacion = new javax.swing.JLabel();
        lDiscipulado = new javax.swing.JLabel();
        lDefinitiva = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        tC1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tC2 = new javax.swing.JTextField();
        tC3 = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lAlumno.setText("Alumno:");

        lIdentificacion.setText("Identificación:");

        lDiscipulado.setText("Discipulado:");

        lDefinitiva.setText("Definitiva:");

        btnCancelar.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Primer corte");

        jLabel6.setText("Segundo corte");

        jLabel7.setText("Tercer corte");

        btnActualizar.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exchange.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setToolTipText("");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDefinitiva)
                            .addComponent(lDiscipulado)
                            .addComponent(lIdentificacion)
                            .addComponent(lAlumno)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActualizar)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tC1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tC2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(tC3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lIdentificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lDiscipulado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lDefinitiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tC1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tC2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tC3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        nD.setCorte1(Float.parseFloat(tC1.getText()));
        nD.setCorte2(Float.parseFloat(tC2.getText()));
        nD.setCorte3(Float.parseFloat(tC3.getText()));
        try{
            if (nD.agregarNota(nD)){
                JOptionPane.showMessageDialog(this, "Nota actualizada exitosamente!");
                calculaDef ();                
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo actualizar las notas"
                        , "Error", JOptionPane.ERROR_MESSAGE);
            }            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Revise que esté ingresando valores correctos"
                        , "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed
    
    private void llenarVentana (){
        String nom = "";
        for (int i=0; i<aLC.size(); i++){
            if (aLC.get(i).getNumIdentificacion() == nD.getCodDiscipulado()){
                nom = "<html><b>Alumno: </b>"+aLC.get(i).getNombres()+" "+aLC.get(i).getApellidos()+"</html>";
            }
        }
        lAlumno.setText(nom);
        lIdentificacion.setText("<html><b>Identificación: </b>"+nD.getIdEstudiante()+"</html>");
        lDiscipulado.setText("<html><b>Discipulado: </b>"+d.getNombre()+"</html>");
        calculaDef();
        tC1.setText(Float.toString(nD.getCorte1()));
        tC2.setText(Float.toString(nD.getCorte2()));
        tC3.setText(Float.toString(nD.getCorte3()));
    }
    
    private void calculaDef (){
        double def = ((nD.getCorte1()*0.3)+(nD.getCorte2()*0.3)+(nD.getCorte3()*0.4));
        DecimalFormat df = new DecimalFormat("0.00");
        lDefinitiva.setText("<html><b>Definitiva: </b>"+df.format(def)+"</html>");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lAlumno;
    private javax.swing.JLabel lDefinitiva;
    private javax.swing.JLabel lDiscipulado;
    private javax.swing.JLabel lIdentificacion;
    private javax.swing.JTextField tC1;
    private javax.swing.JTextField tC2;
    private javax.swing.JTextField tC3;
    // End of variables declaration//GEN-END:variables
}
