/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import logica.Asistencia;
import logica.Congregante;
import logica.Iglesia;

/**
 *
 * @author davi1
 */
public class ControlAsistencia extends javax.swing.JDialog {
    private DefaultListModel lista1;
    private ArrayList<Asistencia> lAsistencia;
    private ArrayList<Congregante> lCongregante;
    /**
     * Creates new form ControlAsistencia
     */
    public ControlAsistencia(java.awt.Frame parent, boolean modal, ArrayList<Asistencia> asis, ArrayList<Congregante> cong) {
        super(parent, modal);
        initComponents();
        this.setResizable(false); //Deshabilita la opción de maximizar la ventana.
        this.setLocationRelativeTo(null); //Centra la ventana
        lAsistencia = asis;
        lCongregante = cong;
        fechaAsistencia.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaAsistencia = new javax.swing.JList<>();
        btnRegistrar = new javax.swing.JButton();
        jTID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        fechaAsistencia = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro y control de asistencia");

        jScrollPane1.setViewportView(listaAsistencia);

        btnRegistrar.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jTID.setText("Ingrese Identificación");
        jTID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTIDMouseClicked(evt);
            }
        });
        jTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIDActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha de asistencia");

        jButton4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow_left1.png"))); // NOI18N
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 325, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(10, 10, 10)
                                        .addComponent(fechaAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(fechaAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTID)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fechaAsistencia.getDateEditor().addPropertyChangeListener(new java.beans.PropertyChangeListener(){
            public void propertyChange(java.beans.PropertyChangeEvent evt){
                agregaListaAsistencia ();
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Congregante c = new Congregante ();
        if (c.buscarC(Long.parseLong(jTID.getText()), lCongregante) != null){
            Asistencia nueva = new Asistencia (); 
            boolean ver = nueva.agregaAsistencia(Long.parseLong(jTID.getText()), new Date());
            if (ver == false){
                JOptionPane.showMessageDialog(this, "No se pudo agregar a la base de datos, revise si "
                        + "existe congregante con ese número", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Asistencia agregado exitosamente!");
                Iglesia ig = new Iglesia ();
                lAsistencia = ig.getListaAsistencia();
                agregaListaAsistencia ();
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIDActionPerformed

    }//GEN-LAST:event_jTIDActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTIDMouseClicked
        jTID.setText("");
    }//GEN-LAST:event_jTIDMouseClicked

    private void agregaListaAsistencia (){
        try{
        lista1 = new DefaultListModel();
        this.listaAsistencia.setModel(lista1);
            //System.out.println(lAsistencia.size());
            for( int i = 0 ; i < lAsistencia.size() ; i++ ){
                Date m = lAsistencia.get(i).getFecha();
                Date n = fechaAsistencia.getDate();
                if (m.getDate()==n.getDate() && m.getMonth()==n.getMonth() && m.getYear()==n.getYear()){
                    for (int j=0; j<lAsistencia.get(i).getAsistentes().size(); j++){
                        Congregante c = new Congregante ();
                        c = c.buscarC(lAsistencia.get(i).getAsistentes().get(j), lCongregante);
                        lista1.addElement("<html><font color='blue' face='Comic Sans MS' size='4'>"+c.getNombres()+" "+c.getApellidos()+"</font><b> -- </b>"
                        + ""+c.getNumIdentificacion()+"</html>");
                    }
                }
            }
        }catch(Exception e){}
    }
    
    /*private ArrayList<Congregante> lFCong (Date f){
        for( int i = 0 ; i < lAsistencia.size() ; i++ ){
            if (lCongregante.get(i).getNumIdentificacion() == id){
                return lCongregante.get(i);
            }
        }
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private com.toedter.calendar.JDateChooser fechaAsistencia;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTID;
    private javax.swing.JList<String> listaAsistencia;
    // End of variables declaration//GEN-END:variables
}
