/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import logica.Congregante;
import logica.Discipulado;
import logica.Iglesia;

/**
 *
 * @author davi1
 */
public class Discipulados extends javax.swing.JDialog {
    private ArrayList<Discipulado> aLD;
    private ArrayList<Congregante> aLC;
    private DefaultListModel lista1;
    private Discipulado foco;
    /**
     * Creates new form VerDiscipulados
     */
    public Discipulados(java.awt.Frame parent, boolean modal, ArrayList<Discipulado> aLD, ArrayList<Congregante> aLC) {
        super(parent, modal);
        initComponents();
        this.setResizable(false); //Deshabilita la opción de maximizar la ventana.
        this.setLocationRelativeTo(null); //Centra la ventana
        this.aLD = aLD;
        this.aLC = aLC;
        actListaDis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnAgregarDis = new javax.swing.JButton();
        btnEditarDis = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lDiscipulado = new javax.swing.JList<>();
        btnVerDis = new javax.swing.JButton();
        btnEliminarDis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Discipulados");

        btnSalir.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAgregarDis.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnAgregarDis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/more_32.png"))); // NOI18N
        btnAgregarDis.setText("Agregar");
        btnAgregarDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDisActionPerformed(evt);
            }
        });

        btnEditarDis.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnEditarDis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pen.png"))); // NOI18N
        btnEditarDis.setText("Editar");
        btnEditarDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDisActionPerformed(evt);
            }
        });

        lDiscipulado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lDiscipuladoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lDiscipulado);

        btnVerDis.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnVerDis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye.png"))); // NOI18N
        btnVerDis.setText("Ver");
        btnVerDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDisActionPerformed(evt);
            }
        });

        btnEliminarDis.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnEliminarDis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gnome_edit_delete.png"))); // NOI18N
        btnEliminarDis.setText("Eliminar");
        btnEliminarDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAgregarDis)
                                .addGap(6, 6, 6)
                                .addComponent(btnEditarDis)
                                .addGap(18, 18, 18)
                                .addComponent(btnVerDis)
                                .addGap(14, 14, 14)
                                .addComponent(btnEliminarDis)
                                .addGap(14, 14, 14))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarDis, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnVerDis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarDis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarDis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDisActionPerformed
        AgregarDiscipulado ad = new AgregarDiscipulado(null, true, aLC);
        ad.setVisible(true);
        Iglesia i = new Iglesia();
        aLD = i.getListaDiscipulados();
        actListaDis();
    }//GEN-LAST:event_btnAgregarDisActionPerformed

    private void btnEditarDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDisActionPerformed
        EditarDiscipulado ed = new EditarDiscipulado(null, true, aLC, foco);
        ed.setVisible(true);
        Iglesia i = new Iglesia();
        aLD = i.getListaDiscipulados();
        actListaDis();
    }//GEN-LAST:event_btnEditarDisActionPerformed

    private void btnVerDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDisActionPerformed
        VerDiscipulado vd = new VerDiscipulado (null, true, aLC, foco);
        vd.setVisible(true);
        Iglesia i = new Iglesia();
        aLD = i.getListaDiscipulados();
    }//GEN-LAST:event_btnVerDisActionPerformed

    private void btnEliminarDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDisActionPerformed
        if (foco.eliminarDiscipulado(foco)){
                JOptionPane.showMessageDialog(this, "Discipulado eliminado exitosamente!");
                for (int i=0; i<aLD.size(); i++){
                    if (foco.getIdDiscipulado()== aLD.get(i).getIdDiscipulado()){
                        aLD.remove(i);
                        actListaDis();  
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar Discipulado"
                        , "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnEliminarDisActionPerformed

    private void lDiscipuladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lDiscipuladoMouseClicked
        try{
            int posicion = lDiscipulado.locationToIndex(evt.getPoint());
            foco = aLD.get(posicion);
            btnEditarDis.setEnabled(true);
            btnVerDis.setEnabled(true);
            btnEliminarDis.setEnabled(true);
        }catch(Exception e){}
    }//GEN-LAST:event_lDiscipuladoMouseClicked

    private void actListaDis(){
        lista1 = new DefaultListModel();
        this.lDiscipulado.setModel(lista1);

            for( int i = 0 ; i < aLD.size() ; i++ ){
                Congregante c = new Congregante ();
                c = c.buscarC(aLD.get(i).getInstructor(), aLC);
                lista1.addElement("<html><font color='blue' face='Comic Sans MS' size='4'>"+aLD.get(i).getNombre()+"</font><br><b>Instructor: </b>"
                        + ""+c.getNombres()+" "+c.getApellidos()+"</html>");
            }
        btnEditarDis.setEnabled(false);
        btnVerDis.setEnabled(false);
        btnEliminarDis.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDis;
    private javax.swing.JButton btnEditarDis;
    private javax.swing.JButton btnEliminarDis;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerDis;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lDiscipulado;
    // End of variables declaration//GEN-END:variables
}
