/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import logica.Congregante;
import logica.Iglesia;
import logica.Ministerio;

/**
 *
 * @author davi1
 */
public class Ministerios extends javax.swing.JDialog {
    private DefaultListModel lista1;
    private ArrayList<Ministerio> aLM;
    private ArrayList<Congregante> aLC;
    private Ministerio foco;
    /**
     * Creates new form Ministerios
     */
    public Ministerios(java.awt.Frame parent, boolean modal, ArrayList<Ministerio> aLM, ArrayList<Congregante> aLC) {
        super(parent, modal);
        initComponents();
        this.setResizable(false); //Deshabilita la opción de maximizar la ventana.
        this.setLocationRelativeTo(null); //Centra la ventana
        this.aLM = aLM;
        this.aLC = aLC;
        actListaMin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        btnAgregarMin = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMinisterio = new javax.swing.JList<>();
        btnVerMin = new javax.swing.JButton();
        btnEliminarMin = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btnEditarMin = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton5.setText("Editar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ministerios");

        btnAgregarMin.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnAgregarMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/more_32.png"))); // NOI18N
        btnAgregarMin.setText("Agregar");
        btnAgregarMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMinActionPerformed(evt);
            }
        });

        listaMinisterio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMinisterioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaMinisterio);

        btnVerMin.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnVerMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye.png"))); // NOI18N
        btnVerMin.setText("Ver");
        btnVerMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMinActionPerformed(evt);
            }
        });

        btnEliminarMin.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnEliminarMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gnome_edit_delete.png"))); // NOI18N
        btnEliminarMin.setText("Eliminar");
        btnEliminarMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMinActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow_left1.png"))); // NOI18N
        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btnEditarMin.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnEditarMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pen.png"))); // NOI18N
        btnEditarMin.setText("Editar");
        btnEditarMin.setToolTipText("");
        btnEditarMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAgregarMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditarMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVerMin)
                                .addGap(14, 14, 14)
                                .addComponent(btnEliminarMin)
                                .addGap(14, 14, 14))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMinActionPerformed
        AgregarMinisterio am = new AgregarMinisterio(null, true, aLC);
        am.setVisible(true);
        Iglesia i = new Iglesia();
        aLM = i.getListaMinisterios();
        actListaMin();
    }//GEN-LAST:event_btnAgregarMinActionPerformed

    private void btnVerMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMinActionPerformed
        VerMinisterio vm = new VerMinisterio (null, true, foco, aLC);
        vm.setVisible(true);
        Iglesia i = new Iglesia();
        aLM = i.getListaMinisterios();
        actListaMin();
    }//GEN-LAST:event_btnVerMinActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnEliminarMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMinActionPerformed
            if (foco.eliminarMinisterio(foco)){
                JOptionPane.showMessageDialog(this, "Ministerio eliminado exitosamente!");
                for (int i=0; i<aLM.size(); i++){
                    if (foco.getCodigo() == aLM.get(i).getCodigo()){
                        aLM.remove(i);
                        actListaMin();    
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar Ministerio"
                        , "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnEliminarMinActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnEditarMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMinActionPerformed
        EditarMinisterio em = new EditarMinisterio(null, true, aLC, foco);
        em.setVisible(true);
        Iglesia i = new Iglesia();
        aLM = i.getListaMinisterios();
        actListaMin();
    }//GEN-LAST:event_btnEditarMinActionPerformed

    private void listaMinisterioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMinisterioMouseClicked
        try{
            int posicion = listaMinisterio.locationToIndex(evt.getPoint());
            foco = aLM.get(posicion);
            btnEditarMin.setEnabled(true);
            btnVerMin.setEnabled(true);
            btnEliminarMin.setEnabled(true);
        }catch(Exception e){}
    }//GEN-LAST:event_listaMinisterioMouseClicked

    private void actListaMin(){
        lista1 = new DefaultListModel();
        this.listaMinisterio.setModel(lista1);

            for( int i = 0 ; i < aLM.size() ; i++ ){
                Congregante c = new Congregante ();
                c = c.buscarC(aLM.get(i).getLider(), aLC);
                lista1.addElement("<html><font color='blue' face='Comic Sans MS' size='4'>"+aLM.get(i).getNombre()+"</font><br><b>Lider: </b>"
                        + ""+c.getNombres()+" "+c.getApellidos()+"</html>");
            }
        btnEditarMin.setEnabled(false);
        btnVerMin.setEnabled(false);
        btnEliminarMin.setEnabled(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMin;
    private javax.swing.JButton btnEditarMin;
    private javax.swing.JButton btnEliminarMin;
    private javax.swing.JButton btnVerMin;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaMinisterio;
    // End of variables declaration//GEN-END:variables
}
