/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import logica.ActividadMinisterio;
import logica.Congregante;
import logica.Iglesia;
import logica.Ministerio;

/**
 *
 * @author davi1
 */
public class VerMinisterio extends javax.swing.JDialog {
    private Ministerio min;
    private ArrayList<Congregante> aLC;
    private Long focoMie;
    private ActividadMinisterio focoAct;
    private DefaultListModel lista1;
    private DefaultListModel lista2;
    /**
     * Creates new form VerMinisterio
     */
    public VerMinisterio(java.awt.Frame parent, boolean modal, Ministerio m, ArrayList<Congregante> aLC) {
        super(parent, modal);
        initComponents();
        this.setResizable(false); //Deshabilita la opción de maximizar la ventana.
        this.setLocationRelativeTo(null); //Centra la ventana
        this.min = m;
        this.aLC = aLC;
        agregaListaMiembros ();
        actListaActividades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaMiembros = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaActividades = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnAMiembro = new javax.swing.JButton();
        btnAActividad = new javax.swing.JButton();
        btnEMiembros = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEActividades = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listaMiembros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMiembrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaMiembros);

        listaActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaActividadesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaActividades);

        jLabel2.setText("Actividades");

        btnAMiembro.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnAMiembro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/more_32.png"))); // NOI18N
        btnAMiembro.setText("Agregar miembros");
        btnAMiembro.setToolTipText("");
        btnAMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAMiembroActionPerformed(evt);
            }
        });

        btnAActividad.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnAActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/more_32.png"))); // NOI18N
        btnAActividad.setText("Agregar actividades");
        btnAActividad.setToolTipText("");
        btnAActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActividadActionPerformed(evt);
            }
        });

        btnEMiembros.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnEMiembros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gnome_edit_delete.png"))); // NOI18N
        btnEMiembros.setText("Eliminar miembros");
        btnEMiembros.setToolTipText("");
        btnEMiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEMiembrosActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow_left1.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setText("Miembros");

        btnEActividades.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnEActividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gnome_edit_delete.png"))); // NOI18N
        btnEActividades.setText("Eliminar actividades");
        btnEActividades.setToolTipText("");
        btnEActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActividadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(215, 215, 215))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSalir)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAActividad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEMiembros)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEActividades))))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAMiembro)
                    .addComponent(btnAActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEMiembros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEActividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAMiembroActionPerformed
        AgregarMiembrosMinisterio amm = new AgregarMiembrosMinisterio(null, true, aLC, min);
        amm.setVisible(true);
        Iglesia ig = new Iglesia();
        for (int i=0; i<ig.getListaMinisterios().size(); i++){
            if (ig.getListaMinisterios().get(i).getCodigo() == min.getCodigo()){
                min = ig.getListaMinisterios().get(i);
            }
        }
        agregaListaMiembros ();
    }//GEN-LAST:event_btnAMiembroActionPerformed

    private void btnAActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActividadActionPerformed
        AgregarActividad aa = new AgregarActividad (null, true, min);
        aa.setVisible(true);
        Iglesia ig = new Iglesia();
        for (int i=0; i<ig.getListaMinisterios().size(); i++){
            if (ig.getListaMinisterios().get(i).getCodigo() == min.getCodigo()){
                min = ig.getListaMinisterios().get(i);
            }
        }
        actListaActividades();
    }//GEN-LAST:event_btnAActividadActionPerformed

    private void btnEMiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEMiembrosActionPerformed
        if (min.eliminarMiembro(min.getCodigo(), focoMie)){
                JOptionPane.showMessageDialog(this, "Miembro eliminado exitosamente!");
                Vector<Long> v = min.getMiembros();
                for (int i=0; i<min.getMiembros().size(); i++){
                    if (focoMie == min.getMiembros().get(i)){
                        v.remove(i);
                        min.setMiembros(v);
                        agregaListaMiembros ();    
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar Ministerio"
                        , "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnEMiembrosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActividadesActionPerformed
        if (focoAct.eliminarActividad(min.getCodigo(), focoAct.getCodActividad())){
                JOptionPane.showMessageDialog(this, "Actividad eliminada exitosamente!");
                ArrayList<ActividadMinisterio> aLAM = min.getActividades();
                for (int i=0; i<min.getActividades().size(); i++){
                    if (focoAct.getCodActividad() == min.getActividades().get(i).getCodActividad()){
                        aLAM.remove(i);
                        min.setActividades(aLAM);
                        actListaActividades();    
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar Ministerio"
                        , "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnEActividadesActionPerformed

    private void listaMiembrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMiembrosMouseClicked
        try{
            int posicion = listaMiembros.locationToIndex(evt.getPoint());
            focoMie = min.getMiembros().get(posicion);
            btnEMiembros.setEnabled(true);
        }catch(Exception e){}
    }//GEN-LAST:event_listaMiembrosMouseClicked

    private void listaActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaActividadesMouseClicked
        try{
            int posicion = listaActividades.locationToIndex(evt.getPoint());
            focoAct = min.getActividades().get(posicion);
            btnEActividades.setEnabled(true);
        }catch(Exception e){}
    }//GEN-LAST:event_listaActividadesMouseClicked

    private void agregaListaMiembros (){
        lista1 = new DefaultListModel();
        this.listaMiembros.setModel(lista1);

            for( int i = 0 ; i < min.getMiembros().size() ; i++ ){
                Congregante c = new Congregante ();
                c = c.buscarC(min.getMiembros().get(i), aLC);
                lista1.addElement("<html><font color='blue' face='Comic Sans MS' size='4'>"+c.getNombres()+" "+c.getApellidos()+"</font><br><b>Identificación: </b>"
                        + ""+c.getNumIdentificacion()+"</html>");
            }
            btnEMiembros.setEnabled(false);
    }
    
    private void actListaActividades(){
        lista2 = new DefaultListModel();
        this.listaActividades.setModel(lista2);

            for( int i = 0 ; i < min.getActividades().size() ; i++ ){
                lista2.addElement("<html><font color='blue' face='Comic Sans MS' size='4'>"+min.getActividades().get(i).getNombre()+"</font><br><b>Fecha: </b>"
                        + ""+new SimpleDateFormat("dd-MM-yyyy").format(min.getActividades().get(i).getFecha())+"<br><b>Descripción: </b>"+min.getActividades().get(i).getDescripcion()+"</html>");
            }
            btnEActividades.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAActividad;
    private javax.swing.JButton btnAMiembro;
    private javax.swing.JButton btnEActividades;
    private javax.swing.JButton btnEMiembros;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaActividades;
    private javax.swing.JList<String> listaMiembros;
    // End of variables declaration//GEN-END:variables
}
